[2022-05-19 02:00:16,084] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: ETL.poblar_tablas.poblar_stock_item manual__2022-05-05T15:19:55.441542+00:00 [queued]>
[2022-05-19 02:00:16,176] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: ETL.poblar_tablas.poblar_stock_item manual__2022-05-05T15:19:55.441542+00:00 [queued]>
[2022-05-19 02:00:16,179] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-05-19 02:00:16,179] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-05-19 02:00:16,181] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-05-19 02:00:16,639] {taskinstance.py:1270} INFO - Executing <Task(PostgresOperator): poblar_tablas.poblar_stock_item> on 2022-05-05 15:19:55.441542+00:00
[2022-05-19 02:00:17,021] {standard_task_runner.py:52} INFO - Started process 3086 to run task
[2022-05-19 02:00:17,574] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL', 'poblar_tablas.poblar_stock_item', 'manual__2022-05-05T15:19:55.441542+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/ELT.py', '--cfg-path', '/tmp/tmplve3tlq5', '--error-file', '/tmp/tmphcu9j4u1']
[2022-05-19 02:00:17,638] {standard_task_runner.py:80} INFO - Job 20: Subtask poblar_tablas.poblar_stock_item
[2022-05-19 02:00:19,404] {logging_mixin.py:109} INFO - Running <TaskInstance: ETL.poblar_tablas.poblar_stock_item manual__2022-05-05T15:19:55.441542+00:00 [running]> on host 096c3bc3ad3a
[2022-05-19 02:00:21,036] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=estudiante@uniandes.edu.co
AIRFLOW_CTX_DAG_OWNER=Estudiante
AIRFLOW_CTX_DAG_ID=ETL
AIRFLOW_CTX_TASK_ID=poblar_tablas.poblar_stock_item
AIRFLOW_CTX_EXECUTION_DATE=2022-05-05T15:19:55.441542+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-05T15:19:55.441542+00:00
[2022-05-19 02:00:21,097] {base.py:79} INFO - Using connection to: id: postgres_localhost. Host: host.docker.internal, Port: 5432, Schema: WWWIDWGrupo16, Login: Grupo16BI, Password: ***, extra: {}
[2022-05-19 02:00:21,958] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 92, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 198, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 113, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError
[2022-05-19 02:00:22,717] {taskinstance.py:1288} INFO - Marking task as FAILED. dag_id=ETL, task_id=poblar_tablas.poblar_stock_item, execution_date=20220505T151955, start_date=20220519T020016, end_date=20220519T020022
[2022-05-19 02:00:23,139] {standard_task_runner.py:98} ERROR - Failed to execute job 20 for task poblar_tablas.poblar_stock_item (; 3086)
[2022-05-19 02:00:23,198] {local_task_job.py:212} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2022-05-19 02:00:23,218] {process_utils.py:124} INFO - Sending Signals.SIGTERM to group 3086. PIDs of all processes in the group: [3086]
[2022-05-19 02:00:23,231] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 3086
[2022-05-19 02:00:23,328] {process_utils.py:70} INFO - Process psutil.Process(pid=3086, status='terminated', exitcode=1, started='02:00:15') (3086) terminated with exit code 1
